GET http://localhost:3000/randomAvatar?gender=male&name=doubled

###

GET http://localhost:3000/randomName?gender=female

###

GET http://localhost:3000/randomOccupation

###

GET http://localhost:3000/randomPersona

###

GET http://localhost:3000/randomPersona?gender=female